#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════════
# reorganize.sh — Capstone C2C Behavioral Dynamics
# Run from the project root:
#   cd ~/path/to/Capstone_C2C_Behavioral_Dynamics
#   bash reorganize.sh
#
# What this does:
#   1. Renames notebooks to clean numbered scheme
#   2. Builds the full results/ subfolder tree
#   3. Copies the new baselines notebook into notebooks/
#   4. Creates src/models/ stubs for each model
#   5. Prints a summary of everything done
#
# Safe: only renames and mkdir — never deletes anything.
# ══════════════════════════════════════════════════════════════════════════════

set -e  # exit on any error
ROOT="$(pwd)"

echo "══════════════════════════════════════════════════════"
echo "  Capstone project reorganization"
echo "  Root: $ROOT"
echo "══════════════════════════════════════════════════════"
echo ""

# ── Guard: must be run from project root ──────────────────────────────────────
if [ ! -d "$ROOT/notebooks" ] || [ ! -d "$ROOT/src" ]; then
    echo "ERROR: Run this script from the Capstone_C2C_Behavioral_Dynamics root."
    echo "       Could not find notebooks/ and src/ directories."
    exit 1
fi

# ══════════════════════════════════════════════════════════════════════════════
# 1. RENAME NOTEBOOKS
# ══════════════════════════════════════════════════════════════════════════════
echo "── 1. Renaming notebooks ────────────────────────────"

NB="$ROOT/notebooks"

rename_nb() {
    local src="$NB/$1"
    local dst="$NB/$2"
    if [ -f "$src" ]; then
        mv "$src" "$dst"
        echo "  renamed  $1  →  $2"
    elif [ -f "$dst" ]; then
        echo "  already  $2  (skipped)"
    else
        echo "  missing  $1  (will be created later)"
    fi
}

# EDA layer
rename_nb "01_eda.ipynb"               "01_eda_merrec.ipynb"
rename_nb "07_eda_electronics.ipynb"   "02_eda_electronics.ipynb"
rename_nb "02_eda_amazon_books.ipynb"  "03_eda_books.ipynb"

# Data prep
rename_nb "02_Subset.ipynb"            "04_subset_merrec_balanced.ipynb"

# Baselines (05 = MerRec, 06 = Electronics, 07 = Books)
# The new baselines notebook will be copied in step 3
rename_nb "03_NFM_training.ipynb"      "08_nfm_baseline.ipynb"

# Novel model: UMAG
rename_nb "06_umag.ipynb"              "09_umag_merrec.ipynb"
rename_nb "08_umag_electronics.ipynb"  "10_umag_electronics.ipynb"
rename_nb "09_umag_books_v3.ipynb"     "11_umag_books.ipynb"

# Analysis & visualisation
rename_nb "04_PCA.ipynb"               "12_pca_embeddings.ipynb"
rename_nb "05_t-SNE.ipynb"             "13_tsne_embeddings.ipynb"

echo ""

# ══════════════════════════════════════════════════════════════════════════════
# 2. BUILD results/ SUBFOLDER TREE
# ══════════════════════════════════════════════════════════════════════════════
echo "── 2. Building results/ tree ────────────────────────"

make_dir() {
    mkdir -p "$1"
    echo "  mkdir  $1"
}

# Checkpoints — one subfolder per model
make_dir "$ROOT/results/checkpoints/umag_merrec"
make_dir "$ROOT/results/checkpoints/umag_electronics"
make_dir "$ROOT/results/checkpoints/umag_books"
make_dir "$ROOT/results/checkpoints/mf_bpr_merrec"
make_dir "$ROOT/results/checkpoints/mf_bpr_electronics"
make_dir "$ROOT/results/checkpoints/mf_bpr_books"
make_dir "$ROOT/results/checkpoints/gru4rec_merrec"
make_dir "$ROOT/results/checkpoints/gru4rec_electronics"
make_dir "$ROOT/results/checkpoints/gru4rec_books"

# Metrics — one subfolder per dataset
make_dir "$ROOT/results/metrics/merrec"
make_dir "$ROOT/results/metrics/electronics"
make_dir "$ROOT/results/metrics/books"

# Figures — one subfolder per notebook stage
make_dir "$ROOT/results/figures/eda"
make_dir "$ROOT/results/figures/baselines"
make_dir "$ROOT/results/figures/umag"
make_dir "$ROOT/results/figures/embeddings"

# Tables — final comparison tables for the paper
make_dir "$ROOT/results/tables"

echo ""

# ══════════════════════════════════════════════════════════════════════════════
# 3. COPY NEW BASELINES NOTEBOOK
# ══════════════════════════════════════════════════════════════════════════════
echo "── 3. Placing baseline notebooks ────────────────────"

# The file generated by Claude — copy it if it exists in Downloads or Desktop
GENERATED="$HOME/Downloads/04_baselines_merrec.ipynb"
TARGET_05="$NB/05_baselines_merrec.ipynb"

if [ ! -f "$TARGET_05" ]; then
    if [ -f "$GENERATED" ]; then
        cp "$GENERATED" "$TARGET_05"
        echo "  copied   04_baselines_merrec.ipynb  →  05_baselines_merrec.ipynb"
    else
        touch "$TARGET_05"
        echo "  created  05_baselines_merrec.ipynb  (placeholder — replace with downloaded file)"
    fi
else
    echo "  already  05_baselines_merrec.ipynb  (skipped)"
fi

# Placeholders for electronics and books baselines (to be built)
for nb in "06_baselines_electronics.ipynb" "07_baselines_books.ipynb"; do
    if [ ! -f "$NB/$nb" ]; then
        touch "$NB/$nb"
        echo "  created  $nb  (placeholder)"
    else
        echo "  already  $nb  (skipped)"
    fi
done

# Final results comparison notebook
FINAL_NB="$NB/14_results_comparison.ipynb"
if [ ! -f "$FINAL_NB" ]; then
    touch "$FINAL_NB"
    echo "  created  14_results_comparison.ipynb  (placeholder)"
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════════
# 4. PLACE paths.py INTO src/utils/
# ══════════════════════════════════════════════════════════════════════════════
echo "── 4. Installing src/utils/paths.py ─────────────────"

PATHS_PY="$ROOT/src/utils/paths.py"
if [ ! -f "$PATHS_PY" ]; then
    echo "  paths.py not found — please copy it from the generated file"
    echo "  (generated separately as paths.py)"
else
    echo "  paths.py already in place ✓"
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════════
# 5. SUMMARY
# ══════════════════════════════════════════════════════════════════════════════
echo "══════════════════════════════════════════════════════"
echo "  Done. Final notebooks/ layout:"
echo "══════════════════════════════════════════════════════"
ls "$NB"/*.ipynb 2>/dev/null | while read f; do
    echo "  $(basename $f)"
done
echo ""
echo "  results/ tree:"
find "$ROOT/results" -type d | sort | while read d; do
    depth=$(echo "$d" | tr -cd '/' | wc -c)
    indent=$(printf '%*s' $((($depth - $(echo "$ROOT/results" | tr -cd '/' | wc -c)) * 2)) '')
    echo "  $indent$(basename $d)/"
done
echo ""
echo "  Next step: add paths.py to src/utils/ then run"
echo "  'from src.utils.paths import P' in any notebook."
echo "══════════════════════════════════════════════════════"
